#pragma once 

enum TypKriteria {
	KRIT_UJ_NAZOV,
	KRIT_UJ_TYP,
	KRIT_UJ_PRISLUSNOST,
	KRIT_UJ_POCET_PRE_PROD,
	KRIT_UJ_POCET_PRODUKTIVNYCH,
	KRIT_UJ_POCET_PO_PROD,
	KRIT_UJ_POCET_OBYVATELOV,
	KRIT_UJ_CELKOVA_VYMERA,
	KRIT_UJ_ZASTAVANA_PLOCHA,
	KRIT_UJ_ZASTAVANOST,
	KRIT_BJ_TYP,
	KRIT_BJ_POCET_OSOB,
	KRIT_BJ_POCET_IZIEB,
	KRIT_BJ_POCET,
	KRIT_UJ_POCET_BJ
};